-- 1. Script of creation of tables, with the restrictions of PK, AK and CHECK.


CREATE TABLE PLAYERS (
NICKNAME VARCHAR2(25) NOT NULL,
"NAME" VARCHAR2(25) NOT NULL,
 SURNAME VARCHAR2(25) NOT NULL,
 GENDER VARCHAR2(1) NOT NULL CHECK (GENDER IN ('F', 'M')),
 BIRTHDATE DATE NOT NULL,
 EMAIL VARCHAR2(50) NOT NULL UNIQUE,
 PASSWORD VARCHAR2(25) NOT NULL,
 PHONENUMBER NUMBER,
 RATING NUMBER DEFAULT 1500 CHECK (RATING >= 0),
 CONSTRAINT PK_PLAYERS PRIMARY KEY (NICKNAME));


CREATE TABLE PLAYER_HAS_TITLE (
TITLEID NUMBER NOT NULL,
PLAYERID VARCHAR2(25)NOT NULL,
CONSTRAINT PK_PLAYER_HAS_TITLE_TITLEID PRIMARY KEY (TITLEID, PLAYERID));


CREATE TABLE TITLES(
TITLEID NUMBER NOT NULL,
TITLENAME VARCHAR2(25)NOT NULL UNIQUE,
CONSTRAINT PK_TITLES PRIMARY KEY(TITLEID));


CREATE TABLE CLUBS(
CLUBID NUMBER NOT NULL, 
NAME VARCHAR2(30) NOT NULL UNIQUE,
DESCRIPTION VARCHAR2(50) NOT NULL,
FOUNDER VARCHAR2(25) NOT NULL,
CONSTRAINT PK_CLUBS PRIMARY KEY(CLUBID));


CREATE TABLE PLAYERS_IN_CLUB(
CLUBID NUMBER NOT NULL,
PLAYERID VARCHAR2(25) NOT NULL,
LEFTDATE DATE,
CONSTRAINT PK_PLAYERS_IN_CLUB PRIMARY KEY(CLUBID,PLAYERID));


CREATE TABLE TOURNAMENTS(
TOURNAMENTID NUMBER NOT NULL,
"NAME" VARCHAR2(25) NOT NULL,
IDORGANIZER VARCHAR2(25) NOT NULL,
IDCLUB NUMBER NOT NULL,
ROUNDS NUMBER NOT NULL,
"DATE" DATE NOT NULL,
PRIZE_DESCRIPTION VARCHAR2(200),
TOURNAMENTTYPE VARCHAR2(25)NOT NULL CHECK(TOURNAMENTTYPE IN('Teams','Individual')),
IDLEAGUE NUMBER,
CONSTRAINT PK_TOURNAMENTS PRIMARY KEY(TOURNAMENTID));
CREATE TABLE PLAYER_PLAY_TOURNAMENT(
IDPLAYERINTOURNAMENT VARCHAR2(25)NOT NULL,
TOURNAMENTID NUMBER NOT NULL,
PLAYERID VARCHAR2(25) UNIQUE NOT NULL,
RANKING NUMBER, 
CONSTRAINT PK_PLAYER_PLAY_TOURNAMENT PRIMARY KEY(IDPLAYERINTOURNAMENT));


CREATE TABLE PLAYER_TEAM(
IDTEAM VARCHAR2(50) NOT NULL, 
IDPLAYERINTOURNAMENT VARCHAR2(25)NOT NULL,
CONSTRAINT PK_PLAYER_TEAM PRIMARY KEY(IDTEAM,IDPLAYERINTOURNAMENT));


CREATE TABLE TEAMS( 
IDTEAM VARCHAR2(50) NOT NULL,
IDTOURNAMENT NUMBER NOT NULL,
"NAME" VARCHAR2(50) NOT NULL UNIQUE,
RANKING NUMBER,
CONSTRAINT PK_TEAMS PRIMARY KEY(IDTEAM));


CREATE TABLE GAMES(
GAMEID VARCHAR2(20) NOT NULL,
TOURNAMENTID NUMBER NOT NULL, 
ROUND NUMBER NOT NULL CHECK(ROUND<=5),
WHITEPLAYER VARCHAR2(25) NOT NULL,
BLACKPLAYER VARCHAR2(25) NOT NULL, 
DATETIME DATE NOT NULL,
RESULT NUMBER CHECK(RESULT IN(0,-1,1)),
CONSTRAINT PK_GAMES PRIMARY KEY(GAMEID),
CONSTRAINT CH_GAMES CHECK(WHITEPLAYER <> BLACKPLAYER));


CREATE TABLE CHAT(
CHATID NUMBER NOT NULL,
NAME VARCHAR2(50) NOT NULL UNIQUE,
TOURNAMENTID NUMBER NOT NULL,
CONSTRAINT PK_CHAT PRIMARY KEY (CHATID));


CREATE TABLE PLAYER_WRITE_CHAT(
CHATID NUMBER NOT NULL,
PLAYERINTOURNAMENTID VARCHAR2(25) NOT NULL,
DATETIME TIMESTAMP NOT NULL,
MESSAGE VARCHAR2(256) NOT NULL,
CONSTRAINT PK_TABLE_WRITE_CHAT PRIMARY KEY(CHATID,PLAYERINTOURNAMENTID,DATETIME));










CREATE TABLE LEAGUES(
IDLEAGUE NUMBER NOT NULL,
NAME VARCHAR2(25) UNIQUE NOT NULL,
CLUBID NUMBER NOT NULL,
STARTDATE DATE NOT NULL,
ENDDATE DATE NOT NULL,
CONSTRAINT PK_LEAGUES PRIMARY KEY(IDLEAGUE));


CREATE TABLE PLAYER_PLAY_LEAGUE(
IDLEAGUE NUMBER NOT NULL,
IDPLAYER VARCHAR2(20) NOT NULL,
RANKING NUMBER,
CONSTRAINT PK_PLAYER_PLAY_LEAGUE PRIMARY KEY(IDLEAGUE,IDPLAYER));


CREATE TABLE REWARD(
REWARDID VARCHAR2(20) NOT NULL,
NAME VARCHAR2(25) NOT NULL,
DESCRIPTION VARCHAR2(200) NOT NULL,
POINTS NUMBER NOT NULL,
GAMES VARCHAR2(25) NOT NULL,
CLUBID NUMBER NOT NULL,
CONSTRAINT PK_REWARD PRIMARY KEY(REWARDID));


CREATE TABLE PLAYER_REWARD(
REWARDID VARCHAR2(25) NOT NULL,
PLAYERID VARCHAR2(25),
DATETIME TIMESTAMP NOT NULL,
CONSTRAINT PK_PLAYER_REWARD PRIMARY KEY(REWARDID,PLAYERID,DATETIME));


CREATE TABLE GIFT(
    GIFTID NUMBER NOT NULL,
    "NAME" VARCHAR2(25) NOT NULL,
    "DESCRIPTION" VARCHAR2(100) NOT NULL,
    STOCK NUMBER NOT NULL,
    "COST" NUMBER NOT NULL,
    GIFTTYPE VARCHAR2(20) NOT NULL CHECK(GIFTTYPE IN ('Merchandising', 'Online')),
    CONSTRAINT PK_GIFT PRIMARY KEY(GIFTID)
);


CREATE TABLE PLAYEROBTAINGIFT (
    GIFTID NUMBER NOT NULL,
    PLAYERID VARCHAR2(25) NOT NULL,
    "DATE" DATE NOT NULL,
    "TIME" TIMESTAMP NOT NULL,
    CONSTRAINT PK_PLAYEROBTAINGIFT PRIMARY KEY (GIFTID, PLAYERID, "DATE", "TIME"));






CREATE TABLE MERCHANDISING(
GIFTID NUMBER NOT NULL,
"SIZE" NUMBER NOT NULL,
WEIGHT NUMBER NOT NULL,
CONSTRAINT PK_MERCHANDISING PRIMARY KEY(GIFTID));


CREATE TABLE "ONLINE"( 
GIFTID NUMBER NOT NULL,
"URL" VARCHAR2(100) NOT NULL,
CONSTRAINT PK_ONLINE PRIMARY KEY(GIFTID));