--2. Script for the deletion of the tables. 


DROP TABLE PLAYER_HAS_TITLE CASCADE CONSTRAINTS; 
DROP TABLE TITLES CASCADE CONSTRAINTS;
DROP TABLE CLUBS CASCADE CONSTRAINTS;
DROP TABLE PLAYERS_IN_CLUB CASCADE CONSTRAINTS; 
DROP TABLE TOURNAMENTS CASCADE CONSTRAINTS; 
DROP TABLE PLAYER_PLAY_TOURNAMENT CASCADE CONSTRAINTS; 
DROP TABLE PLAYER_TEAM CASCADE CONSTRAINTS; 
DROP TABLE TEAMS CASCADE CONSTRAINTS; 
DROP TABLE CHAT CASCADE CONSTRAINTS; 
DROP TABLE PLAYER_WRITE_CHAT CASCADE CONSTRAINTS;
DROP TABLE PLAYERS CASCADE CONSTRAINTS;
DROP TABLE GAMES CASCADE CONSTRAINTS;
DROP TABLE LEAGUES CASCADE CONSTRAINTS;
DROP TABLE PLAYER_PLAY_LEAGUE CASCADE CONSTRAINTS;
DROP TABLE REWARD CASCADE CONSTRAINTS;
DROP TABLE PLAYER_REWARD CASCADE CONSTRAINTS;
DROP TABLE GIFT CASCADE CONSTRAINTS;
DROP TABLE PLAYEROBTAINGIFT CASCADE CONSTRAINTS;
DROP TABLE MERCHANDISING CASCADE CONSTRAINTS;
DROP TABLE "ONLINE" CASCADE CONSTRAINTS;


-- Dropping triggers


DROP SEQUENCE CODE_ORDER;
DROP TRIGGER CODE_ASSIGNER;
DROP TRIGGER CHECK_PLAYERS_IN_CLUB;
DROP TRIGGER UPDATE_PLAYER_RATINGS;
DROP TRIGGER BUY_GIFT;