-- Script for the creation of FK constraints. 


ALTER TABLE PLAYER_HAS_TITLE  ADD CONSTRAINT FK_PLAYER_HAS_TITLE_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(NICKNAME) ON DELETE CASCADE;


ALTER TABLE PLAYER_HAS_TITLE ADD CONSTRAINT FK_PLAYER_HAS_TITLE_TITLEID FOREIGN KEY (TITLEID) REFERENCES TITLES(TITLEID);


ALTER TABLE CLUBS ADD CONSTRAINT FK_CLUB_FOUNDER  FOREIGN KEY (FOUNDER) REFERENCES PLAYERS(NICKNAME);


ALTER TABLE PLAYERS_IN_CLUB ADD CONSTRAINT FK_PLAYERS_IN_CLUB_CLUBID 
FOREIGN KEY (CLUBID) REFERENCES CLUBS(CLUBID);


ALTER TABLE PLAYERS_IN_CLUB ADD CONSTRAINT FK_PLAYERS_IN_CLUB_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(NICKNAME);


ALTER TABLE TOURNAMENTS ADD CONSTRAINT FK_TOURNAMENTS_IDCLUB 
FOREIGN KEY (IDCLUB) REFERENCES CLUBS(CLUBID);


ALTER TABLE TEAMS ADD CONSTRAINT FK_TEAMS_IDTOURNAMENT FOREIGN KEY (IDTOURNAMENT) REFERENCES TOURNAMENTS(TOURNAMENTID);


ALTER TABLE PLAYER_PLAY_TOURNAMENT ADD CONSTRAINT FK_PLAYER_PLAY_TOURNAMENT_TOURNAMENTID FOREIGN KEY (TOURNAMENTID) REFERENCES TOURNAMENTS(TOURNAMENTID);


ALTER TABLE PLAYER_PLAY_TOURNAMENT ADD CONSTRAINT FK_PLAYER_PLAY_TOURNAMENT_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(NICKNAME);


ALTER TABLE PLAYER_TEAM ADD CONSTRAINT FK_PLAYER_TEAM_IDPLAYERINTOURNAMENT FOREIGN KEY (IDPLAYERINTOURNAMENT) REFERENCES PLAYER_PLAY_TOURNAMENT(IDPLAYERINTOURNAMENT);


ALTER TABLE PLAYER_TEAM ADD CONSTRAINT FK_PLAYER_TEAM_IDTEAM FOREIGN KEY (IDTEAM) REFERENCES TEAMS(IDTEAM); 


ALTER TABLE GAMES ADD CONSTRAINT FK_GAMES_TOURNAMENTID FOREIGN KEY (TOURNAMENTID) REFERENCES TOURNAMENTS(TOURNAMENTID);






ALTER TABLE GAMES  ADD CONSTRAINT FK_GAMES_WHITEPLAYER FOREIGN KEY (WHITEPLAYER) REFERENCES PLAYER_PLAY_TOURNAMENT(IDPLAYERINTOURNAMENT);


ALTER TABLE GAMES  ADD CONSTRAINT FK_GAMES_BLACKPLAYER FOREIGN KEY (BLACKPLAYER) REFERENCES PLAYER_PLAY_TOURNAMENT(IDPLAYERINTOURNAMENT);


ALTER TABLE CHAT ADD CONSTRAINT FK_CHAT_TOURNAMENTID FOREIGN KEY (TOURNAMENTID) REFERENCES TOURNAMENTS(TOURNAMENTID) ON DELETE CASCADE;


ALTER TABLE PLAYER_WRITE_CHAT ADD CONSTRAINT FK_PLAYER_WRITE_CHAT_CHATID FOREIGN KEY (CHATID) REFERENCES CHAT(CHATID);


ALTER TABLE PLAYER_WRITE_CHAT ADD CONSTRAINT FK_PLAYER_WRITE_CHAT_PLAYERINTOURNAMENTID FOREIGN KEY (PLAYERINTOURNAMENTID) REFERENCES PLAYER_PLAY_TOURNAMENT(IDPLAYERINTOURNAMENT);


ALTER TABLE LEAGUES ADD CONSTRAINT FK_LEAGUES_CLUBID FOREIGN KEY (CLUBID) REFERENCES CLUBS(CLUBID);


ALTER TABLE PLAYER_PLAY_LEAGUE ADD CONSTRAINT FK_PLAYER_PLAY_LEAGUE_IDLEAGUE FOREIGN KEY (IDLEAGUE) REFERENCES LEAGUES(IDLEAGUE) ON DELETE CASCADE;


ALTER TABLE PLAYER_PLAY_LEAGUE ADD CONSTRAINT FK_PLAYER_PLAY_LEAGUE_IDPLAYER FOREIGN KEY (IDPLAYER) REFERENCES PLAYERS(NICKNAME);


ALTER TABLE REWARD ADD CONSTRAINT FK_REWARD FOREIGN KEY (CLUBID) REFERENCES CLUBS(CLUBID);


ALTER TABLE PLAYER_REWARD ADD CONSTRAINT FK_PLAYER_REWARD_REWARDID FOREIGN KEY (REWARDID) REFERENCES REWARD(REWARDID);


ALTER TABLE PLAYER_REWARD ADD CONSTRAINT FK_PLAYER_REWARD_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(NICKNAME);


ALTER TABLE PLAYEROBTAINGIFT ADD CONSTRAINT FK_PLAYEROBTAINGIFT_GIFTID FOREIGN KEY (GIFTID) REFERENCES GIFT(GIFTID)  ;


ALTER TABLE PLAYEROBTAINGIFT ADD CONSTRAINT FK_PLAYEROBTAINGIFT_PLAYERID FOREIGN KEY (PLAYERID) REFERENCES PLAYERS(NICKNAME) ;


ALTER TABLE MERCHANDISING ADD CONSTRAINT FK_MERCHANDISING_GIFTID FOREIGN KEY (GIFTID) REFERENCES GIFT(GIFTID) ON DELETE CASCADE;


ALTER TABLE "ONLINE" ADD CONSTRAINT FK_ONLINE_GIFTID FOREIGN KEY (GIFTID) REFERENCES GIFT(GIFTID) ON DELETE CASCADE;